# FINAL EXAM - 7MPAML

**FIRST NAME:** Banthita

**LAST NAME:** BOONPUN

**WARNINGS**

If you whish to use the customs functions defined in class it is advised to:
- use the conda environment defined for the class
- store this notebook in the same folder than the other class notebooks

**IMPORTS**

In [ ]:
# for package auto reload
%load_ext autoreload
%autoreload 2

# for better rendering of plots in jupyter notebook
%matplotlib inline

In [86]:
import os
import sys

import pandas as pd
import numpy as np
import math

In [ ]:
# if you whish to use our custom functions
# your should store this notebook in the same
# folder than the other class notebooks
path_to_repo = os.path.dirname(os.getcwd())
print(path_to_repo)

sys.path.insert(0, os.path.join(path_to_repo, 'src'))

# custom module
from emlyon.utils import *

In [ ]:
# your own imports here

**INSTRUCTIONS**

0) Advice: store this notebook and the dataset in the same folder where you stored your class notebooks.

1) Load the dataset `data.csv` into a pandas data frame. The `output` column will be your output/dependent variable (`y`), the other columns your input/independent variables (`x`).

2) Numericalize categorical columns, and replace missing values by medians.

3) Split the data into the first 90% rows for training (rows 0 to 26,999 for `x_train,y_train`), the last 10% rows for validation (rows 27,000 to 29,999 for `x_valid,y_valid`).

4) Pick your favorite ensemble model(s) (such as random forrests, catboost, or XGboost, etc.). Train your model(s) on the training set and finetune your model(s) in order to get the highest validation score.

In [2]:
os.getcwd()

'/Users/kk_isswagger/Desktop'

In [3]:
df = pd.read_csv('data.csv')

In [4]:
df

,unif-0,unif-1,unif-2,unif-3,unif-4,unif-5,unif-6,unif-7,unif-8,unif-9,...,gaus-6,gaus-7,gaus-8,gaus-9,cat-0,cat-1,cat-2,cat-3,cat-4,output
0,0.440283,0.542485,0.433224,NaN,0.462204,0.400081,0.567687,-0.861882,-0.014619,0.376069,...,-0.910102,-3.082792,1.608779,-0.986024,low,NaN,light,absolutely dumb,dumbass,45.210654
1,0.968613,0.328928,0.412372,1.675436,0.350678,0.013372,0.195816,0.207813,-0.800158,0.288520,...,-0.809724,-1.050680,-1.062840,-2.036320,med,NaN,dark,smart,badass,41.502918
2,0.849929,0.188907,0.727982,NaN,0.424932,0.257110,0.263948,-0.843278,-0.579933,0.013779,...,-0.150809,-1.792331,0.410076,-0.651319,very high,casual,light,smart,dumbass,51.915517
3,0.353313,0.331995,0.768454,1.103919,0.701463,0.826400,0.715673,0.826076,-0.690707,0.124366,...,0.561363,-0.059959,-0.784778,-0.299386,low,NaN,dark,smart,jackass,52.397772
4,0.768396,0.451243,0.110242,0.328313,0.164867,0.165148,0.918799,1.812233,-0.992387,0.727247,...,-2.128338,0.171036,0.274399,-0.744216,low,serious,dark,smart,jackass,54.104877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,0.603788,0.071240,0.984987,0.623897,0.382582,0.848774,0.695288,-0.130733,-0.194856,0.512681,...,-0.288749,-3.048947,0.714453,-2.196963,very high,casual,dark,very smart,jackass,77.771132
29996,0.691864,0.511881,0.244566,1.168866,0.116568,0.389593,0.080606,0.278840,-0.680778,0.969385,...,0.014170,-2.246362,0.244325,-1.413219,low,serious,dark,dumb,jackass,35.206713
29997,0.804656,0.437648,0.699431,1.182186,0.896940,0.898772,0.055077,1.101345,-0.852769,0.754163,...,-0.960900,-3.374016,-0.823089,-2.194314,med,casual,light,normal,dumbass,55.863259
29998,0.314106,0.269001,0.929284,1.459230,0.943636,0.670845,0.851314,0.167896,-0.203723,0.235883,...,1.252086,-1.929552,0.661987,-2.559214,low,NaN,light,absolutely dumb,badass,27.838619
29999,0.643895,0.956046,0.702601,NaN,0.647668,0.321013,0.748269,-0.864731,-0.996891,0.836247,...,-2.980262,-2.525941,-1.002379,-2.270698,very high,NaN,light,normal,punkass,76.864429

In [5]:
df.columns

Index(['unif-0', 'unif-1', 'unif-2', 'unif-3', 'unif-4', 'unif-5', 'unif-6',
       'unif-7', 'unif-8', 'unif-9', 'gaus-0', 'gaus-1', 'gaus-2', 'gaus-3',
       'gaus-4', 'gaus-5', 'gaus-6', 'gaus-7', 'gaus-8', 'gaus-9', 'cat-0',
       'cat-1', 'cat-2', 'cat-3', 'cat-4', 'output'],
      dtype='object')

In [6]:
df.dtypes

unif-0    float64
unif-1    float64
unif-2    float64
unif-3    float64
unif-4    float64
unif-5    float64
unif-6    float64
unif-7    float64
unif-8    float64
unif-9    float64
gaus-0    float64
gaus-1    float64
gaus-2    float64
gaus-3    float64
gaus-4    float64
gaus-5    float64
gaus-6    float64
gaus-7    float64
gaus-8    float64
gaus-9    float64
cat-0      object
cat-1      object
cat-2      object
cat-3      object
cat-4      object
output    float64
dtype: object

In [7]:
df.isna().sum()

unif-0        0
unif-1        0
unif-2        0
unif-3     9000
unif-4        0
unif-5        0
unif-6        0
unif-7        0
unif-8     1500
unif-9        0
gaus-0        0
gaus-1        0
gaus-2        0
gaus-3        0
gaus-4        0
gaus-5        0
gaus-6        0
gaus-7        0
gaus-8        0
gaus-9        0
cat-0         0
cat-1     15000
cat-2         0
cat-3         0
cat-4         0
output        0
dtype: int64

In [12]:
df['cat-0'].unique()

array(['low', 'med', 'very high'], dtype=object)

In [16]:
df['cat-0'].replace(['low', 'med', 'very high'],[0,1,2],inplace=True)

In [13]:
df['cat-1'].unique()

array([nan, 'casual', 'serious'], dtype=object)

In [17]:
df['cat-1'].replace(['nan', 'casual', 'serious'],[0,1,2],inplace=True)

In [19]:
df['cat-2'].unique()

array(['light', 'dark'], dtype=object)

In [20]:
df['cat-2'].replace(['light', 'dark'],[0,1],inplace=True)

In [21]:
df['cat-3'].unique()

array([0, 1, 2, 3, 4])

In [22]:
df['cat-3'].replace(['absolutely dumb', 'smart', 'dumb', 'normal', 'very smart'],[0,1,2,3,4],inplace=True)

In [23]:
df['cat-4'].unique()

array(['dumbass', 'badass', 'jackass', 'punkass'], dtype=object)

In [24]:
df['cat-4'].replace(['dumbass', 'badass', 'jackass', 'punkass'],[0,1,2,3],inplace=True)

In [25]:
df

,unif-0,unif-1,unif-2,unif-3,unif-4,unif-5,unif-6,unif-7,unif-8,unif-9,...,gaus-6,gaus-7,gaus-8,gaus-9,cat-0,cat-1,cat-2,cat-3,cat-4,output
0,0.440283,0.542485,0.433224,NaN,0.462204,0.400081,0.567687,-0.861882,-0.014619,0.376069,...,-0.910102,-3.082792,1.608779,-0.986024,0,NaN,0,0,0,45.210654
1,0.968613,0.328928,0.412372,1.675436,0.350678,0.013372,0.195816,0.207813,-0.800158,0.288520,...,-0.809724,-1.050680,-1.062840,-2.036320,1,NaN,1,1,1,41.502918
2,0.849929,0.188907,0.727982,NaN,0.424932,0.257110,0.263948,-0.843278,-0.579933,0.013779,...,-0.150809,-1.792331,0.410076,-0.651319,2,1.0,0,1,0,51.915517
3,0.353313,0.331995,0.768454,1.103919,0.701463,0.826400,0.715673,0.826076,-0.690707,0.124366,...,0.561363,-0.059959,-0.784778,-0.299386,0,NaN,1,1,2,52.397772
4,0.768396,0.451243,0.110242,0.328313,0.164867,0.165148,0.918799,1.812233,-0.992387,0.727247,...,-2.128338,0.171036,0.274399,-0.744216,0,2.0,1,1,2,54.104877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,0.603788,0.071240,0.984987,0.623897,0.382582,0.848774,0.695288,-0.130733,-0.194856,0.512681,...,-0.288749,-3.048947,0.714453,-2.196963,2,1.0,1,4,2,77.771132
29996,0.691864,0.511881,0.244566,1.168866,0.116568,0.389593,0.080606,0.278840,-0.680778,0.969385,...,0.014170,-2.246362,0.244325,-1.413219,0,2.0,1,2,2,35.206713
29997,0.804656,0.437648,0.699431,1.182186,0.896940,0.898772,0.055077,1.101345,-0.852769,0.754163,...,-0.960900,-3.374016,-0.823089,-2.194314,1,1.0,0,3,0,55.863259
29998,0.314106,0.269001,0.929284,1.459230,0.943636,0.670845,0.851314,0.167896,-0.203723,0.235883,...,1.252086,-1.929552,0.661987,-2.559214,0,NaN,0,0,1,27.838619
29999,0.643895,0.956046,0.702601,NaN,0.647668,0.321013,0.748269,-0.864731,-0.996891,0.836247,...,-2.980262,-2.525941,-1.002379,-2.270698,2,NaN,0,3,3,76.864429

In [26]:
df["cat-1"] = df["cat-1"].fillna(int(df["cat-1"].median()))

In [32]:
df["unif-3"] = df["unif-3"].fillna(int(df["unif-3"].median()))

In [33]:
df["unif-8"] = df["unif-8"].fillna(int(df["unif-8"].median()))

In [34]:
df.isna().sum()

unif-0    0
unif-1    0
unif-2    0
unif-3    0
unif-4    0
unif-5    0
unif-6    0
unif-7    0
unif-8    0
unif-9    0
gaus-0    0
gaus-1    0
gaus-2    0
gaus-3    0
gaus-4    0
gaus-5    0
gaus-6    0
gaus-7    0
gaus-8    0
gaus-9    0
cat-0     0
cat-1     0
cat-2     0
cat-3     0
cat-4     0
output    0
dtype: int64

In [37]:
y = df['output']
y

0        45.210654
1        41.502918
2        51.915517
3        52.397772
4        54.104877
           ...
29995    77.771132
29996    35.206713
29997    55.863259
29998    27.838619
29999    76.864429
Name: output, Length: 30000, dtype: float64

In [47]:
X = pd.DataFrame(df, columns=['unif-0', 'unif-1', 'unif-2', 'unif-3', 'unif-4', 'unif-5', 'unif-6',
       'unif-7', 'unif-8', 'unif-9', 'gaus-0', 'gaus-1', 'gaus-2', 'gaus-3',
       'gaus-4', 'gaus-5', 'gaus-6', 'gaus-7', 'gaus-8', 'gaus-9', 'cat-0',
       'cat-1', 'cat-2', 'cat-3', 'cat-4',])

In [48]:
X

,unif-0,unif-1,unif-2,unif-3,unif-4,unif-5,unif-6,unif-7,unif-8,unif-9,...,gaus-5,gaus-6,gaus-7,gaus-8,gaus-9,cat-0,cat-1,cat-2,cat-3,cat-4
0,0.440283,0.542485,0.433224,1.000000,0.462204,0.400081,0.567687,-0.861882,-0.014619,0.376069,...,1.994387,-0.910102,-3.082792,1.608779,-0.986024,0,2.0,0,0,0
1,0.968613,0.328928,0.412372,1.675436,0.350678,0.013372,0.195816,0.207813,-0.800158,0.288520,...,0.330757,-0.809724,-1.050680,-1.062840,-2.036320,1,2.0,1,1,1
2,0.849929,0.188907,0.727982,1.000000,0.424932,0.257110,0.263948,-0.843278,-0.579933,0.013779,...,2.374915,-0.150809,-1.792331,0.410076,-0.651319,2,1.0,0,1,0
3,0.353313,0.331995,0.768454,1.103919,0.701463,0.826400,0.715673,0.826076,-0.690707,0.124366,...,1.077746,0.561363,-0.059959,-0.784778,-0.299386,0,2.0,1,1,2
4,0.768396,0.451243,0.110242,0.328313,0.164867,0.165148,0.918799,1.812233,-0.992387,0.727247,...,2.426343,-2.128338,0.171036,0.274399,-0.744216,0,2.0,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,0.603788,0.071240,0.984987,0.623897,0.382582,0.848774,0.695288,-0.130733,-0.194856,0.512681,...,0.309591,-0.288749,-3.048947,0.714453,-2.196963,2,1.0,1,4,2
29996,0.691864,0.511881,0.244566,1.168866,0.116568,0.389593,0.080606,0.278840,-0.680778,0.969385,...,-0.626908,0.014170,-2.246362,0.244325,-1.413219,0,2.0,1,2,2
29997,0.804656,0.437648,0.699431,1.182186,0.896940,0.898772,0.055077,1.101345,-0.852769,0.754163,...,0.017340,-0.960900,-3.374016,-0.823089,-2.194314,1,1.0,0,3,0
29998,0.314106,0.269001,0.929284,1.459230,0.943636,0.670845,0.851314,0.167896,-0.203723,0.235883,...,-0.095616,1.252086,-1.929552,0.661987,-2.559214,0,2.0,0,0,1
29999,0.643895,0.956046,0.702601,1.000000,0.647668,0.321013,0.748269,-0.864731,-0.996891,0.836247,...,-0.037429,-2.980262,-2.525941,-1.002379,-2.270698,2,2.0,0,3,3

In [44]:
from sklearn.model_selection import train_test_split

In [50]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=42)

In [53]:
from sklearn.ensemble import RandomForestRegressor

In [54]:
model = RandomForestRegressor(n_estimators=10,n_jobs=-1,random_state=42)

In [56]:
model.fit(X_train,y_train)

RandomForestRegressor(n_estimators=10, n_jobs=-1, random_state=42)

In [71]:
preds = model.predict(X_test)

In [87]:
def rmse(y_gold, y_pred): 
    return math.sqrt(((y_gold - y_pred)**2).mean())

In [88]:
def print_score(m, X_train, y_train, X_valid, y_valid):
    print('RMSE on train set: {:.4f}'.format(rmse(m.predict(X_train), y_train)))
    print('RMSE on valid set: {:.4f}'.format(rmse(m.predict(X_test), y_test)))
    print('R^2 on train set: {:.4f}'.format(m.score(X_train, y_train)))
    print('R^2 on valid set: {:.4f}'.format(m.score(X_test, y_test)))
    if hasattr(m, 'oob_score_'): print('R^2 on oob set: {:.4f}'.format(m.oob_score_))
    return

In [89]:
%time model.fit(X_train, y_train)
print_score(model, X_train, y_train, X_test, y_test)

CPU times: user 5.46 s, sys: 56.3 ms, total: 5.52 s
Wall time: 1.73 s
RMSE on train set: 2.2475
RMSE on valid set: 5.1084
R^2 on train set: 0.9751
R^2 on valid set: 0.8714